language: node_js
node_js:
  - 8.9
deploy:
  provider: npm
  email: hudson.graham@gmail.com
  edge: true
  api_key:
    secure: pw6SlhRNLO86M8AtaIhLd+DFRGf5R+hAs2V1Wvc+FSO1WsjC4dxcdC3xj0YoPCFSwX55Zo4/RzbdxCvLhoAw/LdZwIajNMXDdV6XOQ8m/xnEtHlBNPVqv+SVYDBBqA4xX6AlZqsrdf+NLIb19w0UNz4u64ghRg2t68dTU4p18zAy7nKu2OmvovQH4V2nE9xSHvXqkmkIj5YWhY+XOgWsxTV/g+o+SnW5Ip94bKH0QcQbCyeg6eC2+FGcsjrtZfhELsdvoMdDBJfRJFjNXbUHc8xC4L1TGM1grSAdq0YwCzwp40FZcrAa1FlTiHjF7kAULcmokDDY7M5fbS//ZhMDdv0yByd90a5q22HrvVQPeJ5TMuHQ1KK87buBbIHUg6cvQQ0uIwzI1zStNt+kZSZmj4b4XAPhDMuJQRjHFPobQup/Bu4+l6sK6B/hC/gTvTUtGjhMvzet4ibOgbFp0MXLkzXvRtBPos3wmJVV+FkGFkQb9+xXCw0oweMlop+/owdcbkkdAbavEP9n9dEVBPoW3SeI2XB1/bs4X0nxsH0DKXFGSKd/pKOPHtmc+23dCp0V6vKiotcHqvEVUTRueZu0qnWxsH17AxECvDkx1HXwtLDyxNupyfsesGPOxl671Al+KuGopk2BAdubir4dlvsdqOYFv01o/HM80+KHYXeRUxY=
