/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PxlyButton {
    'color': "primary" | "accent" | "light";
    'disabled': boolean;
    'shape': "square" | "round";
    'size': "small" | "default" | "large";
    'type': "button" | "reset" | "submit";
  }
  interface PxlyTab {
    'active': boolean;
    'disabled': boolean;
    'label': string;
  }
  interface PxlyTabs {
    'openTab': (index: number) => Promise<void>;
  }
}

declare global {


  interface HTMLPxlyButtonElement extends Components.PxlyButton, HTMLStencilElement {}
  var HTMLPxlyButtonElement: {
    prototype: HTMLPxlyButtonElement;
    new (): HTMLPxlyButtonElement;
  };

  interface HTMLPxlyTabElement extends Components.PxlyTab, HTMLStencilElement {}
  var HTMLPxlyTabElement: {
    prototype: HTMLPxlyTabElement;
    new (): HTMLPxlyTabElement;
  };

  interface HTMLPxlyTabsElement extends Components.PxlyTabs, HTMLStencilElement {}
  var HTMLPxlyTabsElement: {
    prototype: HTMLPxlyTabsElement;
    new (): HTMLPxlyTabsElement;
  };
  interface HTMLElementTagNameMap {
    'pxly-button': HTMLPxlyButtonElement;
    'pxly-tab': HTMLPxlyTabElement;
    'pxly-tabs': HTMLPxlyTabsElement;
  }
}

declare namespace LocalJSX {
  interface PxlyButton {
    'color'?: "primary" | "accent" | "light";
    'disabled'?: boolean;
    'shape'?: "square" | "round";
    'size'?: "small" | "default" | "large";
    'type'?: "button" | "reset" | "submit";
  }
  interface PxlyTab {
    'active'?: boolean;
    'disabled'?: boolean;
    'label'?: string;
  }
  interface PxlyTabs {
    'onChange'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'pxly-button': PxlyButton;
    'pxly-tab': PxlyTab;
    'pxly-tabs': PxlyTabs;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pxly-button': LocalJSX.PxlyButton & JSXBase.HTMLAttributes<HTMLPxlyButtonElement>;
      'pxly-tab': LocalJSX.PxlyTab & JSXBase.HTMLAttributes<HTMLPxlyTabElement>;
      'pxly-tabs': LocalJSX.PxlyTabs & JSXBase.HTMLAttributes<HTMLPxlyTabsElement>;
    }
  }
}


