/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PxlyButton {
    'color': "primary" | "accent" | "light";
    'disabled': boolean;
    'shape': "square" | "round";
    'size': "small" | "default" | "large";
    'type': "button" | "reset" | "submit";
  }
}

declare global {


  interface HTMLPxlyButtonElement extends Components.PxlyButton, HTMLStencilElement {}
  var HTMLPxlyButtonElement: {
    prototype: HTMLPxlyButtonElement;
    new (): HTMLPxlyButtonElement;
  };
  interface HTMLElementTagNameMap {
    'pxly-button': HTMLPxlyButtonElement;
  }
}

declare namespace LocalJSX {
  interface PxlyButton {
    'color'?: "primary" | "accent" | "light";
    'disabled'?: boolean;
    'shape'?: "square" | "round";
    'size'?: "small" | "default" | "large";
    'type'?: "button" | "reset" | "submit";
  }

  interface IntrinsicElements {
    'pxly-button': PxlyButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pxly-button': LocalJSX.PxlyButton & JSXBase.HTMLAttributes<HTMLPxlyButtonElement>;
    }
  }
}


